config/routes.rb
Rails.application.routes.draw do
  get 'link/show'
    #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(user) { user.admin? } do
    #mount Blazer::Engine, at: "blazer"
  end

  # Defines the root path route ("/")

  resources :syndics do
    resources :coproperties do
      resources :owners
      resources :budgets
      resources :expenses
      resources :payments, except: [:create]
      resources :messages, only: [:create, :index, :delete]
      resources :properties
      resources :requests, except: [:create, :delete]
    end
  end

  resources :owners do
    resources :coproperties, only: [:show] do
      resources :budgets, only: [:show, :index]
      resources :expenses, only: [:show, :index]
      resources :payments, only: [:new, :create, :show, :index]
      resources :messages, only: [:create, :index]
      resources :properties, only: [:show, :index]
      resources :requests, only: [:new, :create, :show, :index]
    end
  end

  resources :users do
    resources :owners
  end

  resources :coproperties do
    resources :owners, only: [:index]
  end

  get '/syndics/:syndic_id/coproperties/:coproperty_id/dashboard', to: 'pages#syndic_dashboard', as: 'syndic_dashboard'
  get '/owners/:owner_id/coproperties/:coproperty_id/dashboard', to: 'pages#owner_dashboard', as: 'owner_dashboard'


  post '/expenses/:id/up_vote', to: 'expenses#up_vote', as: 'upvote_expense'
  post '/expenses/:id/down_vote', to: 'expenses#down_vote', as: 'downvote_expense'

 get '/links/:id', to: 'links#show', as: 'link'
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :user
  has_many :properties
  has_many :coproperties, through: :properties
  has_one_attached :photo, dependent: :destroy

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @coproperty = Coproperty.find(params[:coproperty_id])
    if current_user.is_syndic?
      @owners = @coproperty.owners
    else
      @owners = current_user.owner.coproperties.first.owners
    end
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    @owner.user = current_user
    @property = Property.find(params[:owner][:property_id])
    if @owner.save
      @property.owner = @owner
      @property.save
      redirect_to owner_path @owner, :notice => "Résident créé !"
    else
      render :action => 'new'
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    if @owner.update(owner_params)
      redirect_to owner_path(current_user.owner), :notice  => "Résident mis à jour!"
    else
      render :action => 'edit'
    end
  end

  def delete
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_url, :notice => "Résident supprimé !"
  end

private

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :gender, :card_number, :phone_number, :ownership_date, :birth_date, :user_id, :photo)
  end

end

app/views/owners/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h3>Fiche propriétaire</h3>

           <%= simple_form_for [@owner] do |f| %>
            <%= f.input :first_name, :label => 'Nom' %>
            <%= f.input :last_name, :label => 'Prénom'%>
            <%= f.input :gender, collection:['homme','femme'], :label => 'Genre'%>
            <%= f.input :phone_number, :label => 'Numéro de téléphone'%>
            <%= f.input :ownership_date, :label => "Date d'achat"%>
            <%= f.input :birth_date, :label => 'Date de naissance'%>
            <%= f.input :photo, :label => 'Photo', :hint => 'Ajoutez une photo', as: :file %>
            <%= f.submit 'Soumettre',class: "btn btn-primary w-100 " %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/owners/_navbar_owner.html.erb
   <div class="menu-btn">
  <%# <div class="menu-btn" style="visibility: hidden;"> %>
     <i class="fas fa-bars"></i>
   </div>
   <div class="side-bar">
   <%# <div class="side-bar active"> %>
     <header>
     <div class="close-btn">
       <i class="fas fa-times"></i>
     </div>
     <%= image_tag "logowhite.png" %>
        </header>
     <div class="menu">

       <div class="item">
       <%= link_to owner_dashboard_path(current_user.owner,coproperty) do %>
       <i class="fas fa-desktop"></i>
       Tableau de Bord
       <% end %>
       </div>

      <div class="item">
       <%= link_to owner_path(current_user.owner,coproperty) do %>
       <i class="fa-solid fa-user"></i>
       Mon Profil
       <% end %>
       </div>

       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-house"></i>Ma Copropriété<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
          <%= link_to owner_coproperty_properties_path(current_user.owner,coproperty), class: "sub-item" do %>
            Mes Propriétés
          <% end %>

          <%= link_to coproperty_owners_path(coproperty), class: "sub-item" do %>
            Mes Voisins
          <% end %>

         </div>
       </div>
       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-message"></i>Communication<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
          <%= link_to owner_coproperty_requests_path(current_user.owner,coproperty), class: "sub-item" do %>
            Mes Requêtes
          <% end %>
           <%= link_to owner_coproperty_messages_path(current_user.owner,coproperty), class: "sub-item" do %>
            Chatroom
          <% end %>
         </div>
       </div>
       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-coins"></i>Mes Finances<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
           <%= link_to owner_coproperty_budgets_path(current_user.owner,coproperty), class: "sub-item" do %>
            Mes Budgets
          <% end %>
           <%= link_to owner_coproperty_expenses_path(current_user.owner,coproperty), class: "sub-item" do %>
            Mes Frais
          <% end %>
           <%= link_to owner_coproperty_payments_path(current_user.owner,coproperty), class: "sub-item" do %>
            Mes Paiements
          <% end %>
         </div>
       </div>
       <div class="item">
          <%= link_to destroy_user_session_path, class: "log-out",  data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion </a>
          <% end %>
        </div>
   </div>

app/views/owners/_owner-form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h2>Formulaire proprietaire à compléter</h2>

        <%= simple_form_for @owner do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :gender, collection:['homme','femme']%>
        <%= f.input :phone_number %>
        <%= f.input :ownership_date %>
        <%= f.input :birth_date %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>

app/views/owners/_owner_info.html.erb
<div class="container" data-controller="dropdown-menus">
  <div class="blur co-shadow syn-profile">
    <div class="p-4 d-flex justify-content-start align-items-center flex-wrap">
      <div class=" w-auto m-4">
       <% if !owner.photo.key.nil? %>
          <%= cl_image_tag owner.photo.key, class: "rounded-circle shadow-1-strong tes-img profile-height", width:"150", height:"150" %>
        <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80", class: "rounded-circle shadow-1-strong tes-img profile-height", width:"150", height:"150" %>
        <% end %>
      </div>
      <div class="information lh-3">
        <h1><%= owner.full_name %></h1>
        <h5 class="mb-3"><i class="fa-solid fa-envelope"></i>&nbsp;&nbsp;<%= owner.user.email  %></h5>
        <h5 class="mb-3"><i class="fa-solid fa-user"></i>&nbsp;&nbsp;<%= "Propriétaire" if owner.user.role.to_s %></h5>
        <h5 class="mb-3"><i class="fa-solid fa-building"></i>&nbsp;&nbsp;<span class="fw-semibold"><%= owner.properties.count %></span> propriétés</h5>
        <div class="p-absolute dots-menu blur d-none" data-dropdown-menus-target="editMenu">
          <%= link_to "Modifier", root_path, class: "dropdown-item dropdown-button fw-semibold" %>
          <%= link_to "Supprimer", root_path, data: {turbo_method: :delete, turbo_confirm: 'êtes-vous sur de vouloir supprimer votre profile', class: "dropdown-item dropdown-button fw-semibold" }%>
        </div>
        <div class="p-absolute three-dots blur" data-action="click->dropdown-menus#toggleMenuTwo">
          <i class="fa-solid fa-ellipsis-vertical"></i>
        </div>
        <div class="d-flex justify-content-between mb-3">
          <span><i class="fa-regular fa-calendar-days"></i>&nbsp;&nbsp;<%= owner.ownership_date %></span>
          <%= link_to destroy_user_session_path do %>
            <i class="fa-solid fa-right-from-bracket"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/owners/edit.html.erb
  <div class="container">
    <h1>Modify owner attributes</h1>
      <div class="mt-3">
        <%= render "form", owner: @owner %>
      </div>
  </div>

app/views/owners/index.html.erb
<div class="d-flex justify-content-center mt-5 container flex-wrap">
    <% @owners.each do |owner| %>
      <div class="notification shadow p-4 owner-photo">
      <% if !owner.photo.key.nil? %>
        <%= cl_image_tag owner.photo.key %>
      <% else %>
        <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80" %>
      <% end %>
      <div class="notification-content">
       <h4 class="ms-3"><strong><%= owner.full_name %></strong></h4>
        <ul class="list-unstyled mt-2 ms-3 owner-icons">
          <li>
            <i class="fa-solid fa-venus-mars"></i> <%= owner.gender %>
          </li>
          <li>
            <i class="fa-solid fa-cake-candles"></i> <%= owner.birth_date %>
          </li>
          <li>
            <i class="fa-solid fa-phone"></i> <%= owner.phone_number %>
          </li>
          <li>
            <i class="fa-solid fa-envelope"></i> <%= owner.user.email %>
          </li>
          <% if current_user.is_syndic? %>
            <li>
              <i class="fa-solid fa-address-card"></i> <%= owner.card_number %>
            </li>
          <% end %>
          <li>
            <i class="fa-solid fa-calendar-days"></i> <%= owner.ownership_date %>
          </li>
        </ul>
      </div>

      <div class="notification-actions flex-wrap align-content-start">
        <% if current_user.is_syndic? %>
        <a href="#"><i class="fas fa-pencil-alt"></i></a>
        <a href="#"><i class="far fa-trash-alt"></i></a>
      <% end %>
      </div>
    </div>
    <% end %>
  </div>

<%# pour plusieurs espaces : %>
<%# &nbsp; %>

app/views/owners/index_test.html.erb
<h1>Mes Propriétaires</h1>

    <% @owners.each do |owner| %>
      <div class="m-4 card-border">
  <div class="container info-card card-dem">
    <div class="row">
      <%# <img src= <%=  "#{@syndic.photo}" %>
      <span class="info-top col">
        <li>Sexe: <%= owner.gender %></li>
        <li>Prénom: <%= owner.first_name %></li>
        <li>Nom de famille: <%= owner.last_name %></li>
        <li>Age: <%= owner.birth_date %></li>
        <li>CIN: <%= owner.card_number %></li>
        <li>GSM: <%= owner.phone_number %></li>
        <li>Propriétaire depuis: <%= owner.ownership_date %></li>
        <% if !owner.photo.key.nil? %>
          <%= cl_image_tag owner.photo.key, class: "img-fluid img-responsive rounded product-image" %>
        <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80", class: "img-fluid img-responsive rounded product-image" %>
        <% end %>
        <div class="info-bottom col-8 search-btns">
        </div>
      </span>
    </div>
    <%# <%= link_to "Update", edit_owner_path(owner.id), class: ""  if current_user.is_syndic? %>

  </div>
    </div>

    <% end %>

<%# <%= button_to "Create new owner", new_owner_path, method: :get %>

<div class="notification">
  <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
  <div class="notification-content">
    <p><strong>14th January</strong></p>
    <ul>
      <li>Coffee</li>
      <li>Tea</li>
      <li>Milk</li>
    </ul>
  </div>

  <div class="notification-actions">
    <a href="#">Edit <i class="fas fa-pencil-alt"></i></a>
    <a href="#">Delete <i class="far fa-trash-alt"></i></a>
  </div>
</div>

<div class="notification">
  <img src='https://kitt.lewagon.com/placeholder/users/Eschults' class="avatar-large"/>
  <div class="notification-content">
    <p><small>9th January</small></p>
    <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipisicing elit.</p>
  </div>

  <div class="notification-actions">
    <a href="#">Edit <i class="fas fa-pencil-alt"></i></a>
    <a href="#">Delete <i class="far fa-trash-alt"></i></a>
  </div>
</div>

app/views/owners/new.html.erb
<div class="" style="position: absolute; bottom: 0; right: 102px;">
  <%= image_tag "Login-svg1.svg" %>
</div>

<div class="" style="position: absolute; bottom: 0; left: 102px;">
  <%= image_tag "login-svg2.svg" %>
</div>

  <%# <h5 class="center-txt features-h fw-bold pb-3">Formulaire propriétaire à compléter</h5> %>
        <div class="container py-5">
        <%= render "form", owner: @owner %>
      </div>

app/views/owners/show.html.erb
<div class="m-4 card-border">
  <div class="container info-card card-dem">
    <div class="row">
      <%# <img src= <%=  "#{@syndic.photo}" %>
      <span class="info-top col">
        <li>Sexe: <%= @owner.gender %></li>
        <li>Prénom: <%= @owner.first_name %></li>
        <li>Nom de famille: <%= @owner.last_name %></li>
        <li>Age: <%= @owner.birth_date %></li>
        <li>CIN: <%= @owner.card_number %></li>
        <li>GSM: <%= @owner.phone_number %></li>
        <li>Propriétaire depuis: <%= @owner.ownership_date %></li>
        <% if !@owner.photo.key.nil? %>
          <%= cl_image_tag @owner.photo.key, class: "img-fluid img-responsive rounded product-image" %>
        <% else %>
          <%= image_tag "https://img.freepik.com/vecteurs-premium/profil-personnage-dessin-anime-avatar-homme-affaires_18591-50581.jpg?w=2000" %>
        <% end %>
        <div class="info-bottom col-8 search-btns">
        </div>
      </span>
    </div>
    <%= link_to "Modifier", edit_owner_path(@owner.id), class: "" %>
  </div>


    </div>
</div>
</div>
</div>