config/routes.rb
Rails.application.routes.draw do
  get 'link/show'
    #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(user) { user.admin? } do
    #mount Blazer::Engine, at: "blazer"
  end

  # Defines the root path route ("/")

  resources :syndics do
    resources :coproperties do
      resources :owners
      resources :budgets
      resources :expenses
      resources :payments, except: [:create]
      resources :messages, only: [:create, :index, :delete]
      resources :properties
      resources :requests, except: [:create, :delete]
    end
  end

  resources :owners do
    resources :coproperties, only: [:show] do
      resources :budgets, only: [:show, :index]
      resources :expenses, only: [:show, :index]
      resources :payments, only: [:new, :create, :show, :index]
      resources :messages, only: [:create, :index]
      resources :properties, only: [:show, :index]
      resources :requests, only: [:new, :create, :show, :index]
    end
  end

  resources :users do
    resources :owners
  end

  resources :coproperties do
    resources :owners, only: [:index]
  end

  get '/syndics/:syndic_id/coproperties/:coproperty_id/dashboard', to: 'pages#syndic_dashboard', as: 'syndic_dashboard'
  get '/owners/:owner_id/coproperties/:coproperty_id/dashboard', to: 'pages#owner_dashboard', as: 'owner_dashboard'


  post '/expenses/:id/up_vote', to: 'expenses#up_vote', as: 'upvote_expense'
  post '/expenses/:id/down_vote', to: 'expenses#down_vote', as: 'downvote_expense'

 get '/links/:id', to: 'links#show', as: 'link'
end

app/models/coproperty.rb
class Coproperty < ApplicationRecord
  belongs_to :syndic
  has_many :properties, dependent: :destroy
  has_many :budgets, dependent: :destroy
  has_many :owners, through: :properties
  has_many :messages, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
end

app/controllers/coproperties_controller.rb
class CopropertiesController < ApplicationController
  before_action :find_coproperty, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.is_syndic?
      @coproperties = current_user.syndic.coproperties
    else
      @coproperties = current_user.owner.coproperties
    end
  end

  def show
    @coproperty = Coproperty.find(params[:id])
    @budget = @coproperty.budgets.first
    if current_user.is_syndic?
      render "pages/syndic_dashboard"
    else
      render "pages/owner_dashboard"
    end
  end

  def new
    @coproperty = Coproperty.new
  end

  def create
    @coproperty = Coproperty.new(coproperty_params)
    @coproperty.syndic = current_user.syndic
    if @coproperty.save
    redirect_to syndic_coproperties_path, :notice => "Copropriété créée !"
    else
    render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @coproperty.update(coproperty_params)
    redirect_to syndic_coproperty_path(current_user.syndic, @coproperty), :notice  => "Copropriété mise à jour!"
    else
    render :action => 'edit'
    end
  end

  def destroy
    @coproperty.destroy
    redirect_to syndic_coproperties_path, :notice => "Copropriété supprimée !"
  end

private

  def coproperty_params
    params.require(:coproperty).permit(:coproperty_name, :number_properties, :address, :expense_method, :coprop_private_area, :coprop_common_area, :photo, :bank_account, :syndic_id)
  end

  def find_coproperty
    @coproperty = Coproperty.find(params[:id])
  end

end

app/views/coproperties/_form.html.erb
<div class="container cop-new">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
       <div class="bg-white-trans-low blur p-4 b-radius shadow">

        <h4 class="mb-4 mt-0">Fiche Copropriété</h4>
        <%= simple_form_for [current_user.syndic, @coproperty] do |f| %>
          <div class="d-flex flex-wrap justify-content-start">
            <%= f.input :coproperty_name, :label => 'Nom', html: { class: "flex-grow" }%>
            <%= f.input :number_properties, :label => 'Nombre de Propriétés' %>
          </div>
          <div class="d-flex flex-wrap justify-content-start">
            <%= f.input :bank_account, :label => 'Numéro de Compte Bancaire', html: { class: "flex-grow" } %>
            <%= f.input :expense_method, :label => 'Méthode de Facturation', collection:['Fixe par Habitant','Variable au Tantième']%>
          </div>
          <%= f.input :address, :label => 'Adresse' %>
          <div class="d-flex flex-wrap justify-content-start">
            <%= f.input :coprop_private_area, :label => 'Surface Privée Totale', :hint => 'Somme des surfaces privées de toutes les propriétés, en m²', class: "w-50" %>
            <%= f.input :coprop_common_area, :label => 'Surface Commune Totale', :hint => 'Somme de la surface commune de la copropriété, en m²', class: "w-50" %>
          </div>
          <%= f.input :photo, :label => 'Photo',:hint => 'Ajoutez une photo de la copropriété', as: :file %>
          <div class="d-flex flex-wrap justify-content-end">
            <%= f.submit 'Soumettre',class: "btn btn-primary w-100 " %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coproperties/_index_sidebar.html.erb
   <div class="menu-btn">
     <i class="fas fa-bars"></i>
   </div>
   <div class="side-bar">
     <header>
     <div class="close-btn">
       <i class="fas fa-times"></i>
     </div>
     <%= image_tag "logowhite.png" %>
        </header>
     <div class="menu">
        <div class="item">
          <%= link_to syndic_coproperties_path(current_user.syndic) do %>
            <i class="fa-solid fa-house"></i>Mes Copropriétés
          <% end %>
        </div>

        <div class="item">
          <%= link_to destroy_user_session_path, class: "log-out",  data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion </a>
          <% end %>
        </div>
     </div>
   </div>

app/views/coproperties/_show_sidebar.html.erb
   <div class="menu-btn">
  <%# <div class="menu-btn" style="visibility: hidden;"> %>
     <i class="fas fa-bars"></i>
   </div>
   <div class="side-bar">
   <%# <div class="side-bar active"> %>
     <header>
     <div class="close-btn">
       <i class="fas fa-times"></i>
     </div>
     <%= image_tag "logowhite.png" %>
        </header>
     <div class="menu">
       <div class="item">
       <%= link_to syndic_coproperty_path(current_user.syndic,coproperty) do %>
       <i class="fas fa-desktop"></i>
       Tableau de Bord
       <% end %>
       </div>

       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-house"></i>Ma Copropriété<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
          <%= link_to syndic_coproperty_properties_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Propriétés
          <% end %>

          <%= link_to syndic_coproperty_owners_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Résidents
          <% end %>

         </div>
       </div>
       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-message"></i>Communication<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
          <%= link_to syndic_coproperty_requests_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Requêtes
          <% end %>
           <%= link_to syndic_coproperty_messages_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Chatroom
          <% end %>
         </div>
       </div>
       <div class="item">
         <a class="sub-btn"><i class="fa-solid fa-coins"></i>Mes Finances<i class="fas fa-angle-right dropdown"></i></a>
         <div class="sub-menu">
           <%= link_to syndic_coproperty_budgets_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Budgets
          <% end %>
           <%= link_to syndic_coproperty_expenses_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Frais
          <% end %>
           <%= link_to syndic_coproperty_payments_path(current_user.syndic,coproperty), class: "sub-item" do %>
            Mes Paiements
          <% end %>
         </div>
       </div>
       <div class="item">
          <%= link_to destroy_user_session_path, class: "log-out",  data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-arrow-right-from-bracket"></i> Déconnexion </a>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/coproperties/edit.html.erb
  <div class="container" data-controller="coproperty-new">
  <h1>Modifiez votre copropriété</h1>
    <div class="" style="position: absolute; bottom: 0; right: 32px;">
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="" style="position: absolute; bottom: 0; left: 32px; transform: rotateY(180deg);">
      <%= image_tag "man-with-paper.svg" %>
    </div>
   <%= render "form", coproperty: @coproperty %>
  </div>

app/views/coproperties/index.html.erb
<div class="container main"
      data-controller="profile-popup">
  <%# profile container %>
  <div class="p-absolute profile-popup d-none"
        data-profile-popup-target="profileContainer">
    <% @syndic = current_user.syndic %>
    <%= render "syndics/show" %>
  </div>
  <%# top container %>
  <div class="container map-container mx-2 my-4 d-flex justify-content-between align-items-center ">


    <span class="fw-regular"> <h1>Bonjour, <%= current_user.syndic.syndic_name %> !</h1></span>
    <div class="profile-div ">
    <%= link_to "Ajouter une copropriété", new_syndic_coproperty_path(current_user.syndic), class: "btn btn-primary fw-semibold" %>
    <div class=" w-auto m-4 "
          data-action="click->profile-popup#toggleProfile">
      <%= image_tag 'syndic', class: "rounded-circle shadow-1-strong small-profile", width:"150", height:"150" %>
    </div>
    </div>
  </div>

  <div class="container m-2 rounded red-border">
    <div class="flex-tabs gap-4 cop-card-section">
        <% @coproperties.each do |coproperty| %>
              <div class="cop-card relative"
                    data-controller="coproperty-card"
                    data-coproperty-info-cop-id-value="<%= coproperty.id %>"
                    data-action="mouseover->coproperty-card#showThreeDots mouseout->coproperty-card#hideThreeDots">
                  <% if coproperty.photo.key %>
                    <%= cl_image_tag coproperty.photo.key, class: "w-100 product-image" %>
                  <% else %>
                    <%= image_tag 'residence.jpg', class: "w-100 product-image" %>
                  <% end %>
                <div class="m-3">
                  <h5><strong><%= coproperty.coproperty_name %></strong></h5>
                  <div class="d-flex flex-row">
                    <%# maybe used later %>
                  </div class="">
                  <div class="mx-1"><i class="fa-solid fa-house"></i>&nbsp;<%= coproperty.number_properties %>&nbsp;propriétés</div>
                  <div class="mx-1 text-justify text-truncate para mb-0"><i class="fa-solid fa-location-dot"></i>&nbsp;<%= coproperty.address %></div>
                  <div class="mx-1"><i class="fa-solid fa-map"></i>&nbsp;<%= coproperty.coprop_private_area + coproperty.coprop_common_area %>m²</div>
                  <div class="mx-1"><i class="fa-solid fa-building"></i>&nbsp;<%= coproperty.building_type %></div>
                  <%# to be calculated %>
                  <h6 class="mx-1 text-success"> <%= rand 7..coproperty.number_properties %>/<%= coproperty.number_properties %> propriétés payées</h6>
                   <%# <%= coproperty.properties.map{ |property| property.paid }.count(true) %>
                    <%# / <%= coproperty.properties.count %>
                <div class="d-flex justify-content-end w-100">
                  <% if current_user.is_syndic? %>
                    <%= link_to "Accéder", syndic_coproperty_path(current_user.syndic, coproperty.id), class: "btn btn-primary fw-semibold"  %>
                  <% else %>
                    <%= link_to "Accéder", owner_coproperty_path(current_user.owner, coproperty.id), class: "btn btn-outline-primary btn-sm mt-2"  %>
                  <% end %>
                </div>
                </div>
                <%# invisible box for toggle %>
                <div class="p-absolute dynamic-box"
                      data-action="mousein->coproperty-card#showMenu mouseout->coproperty-card#hideMenu">
                </div>
                <%# dropdown menu %>
                <div class="p-absolute dots-menu blur d-none"
                      data-coproperty-card-target="dropDown"
                      data-action="mouseout->coproperty-card#toggleMenu"
                      >
                  <% if current_user.is_syndic? %>
                    <%= link_to "Modifier", edit_syndic_coproperty_path(current_user.syndic, coproperty), class: "dropdown-item dropdown-button fw-semibold" %>
                    <%= link_to "Supprimer", syndic_coproperty_path(current_user.syndic, coproperty), data: {turbo_method: :delete, turbo_confirm: 'êtes-vous sur de vouloir supprimer cette copropriété?'}, class: "dropdown-item dropdown-button fw-semibold" %>
                  <% end %>
                </div>
                <%# three dots %>
                <div class="p-absolute three-dots blur d-none"
                      data-action="click->coproperty-card#toggleMenu"
                      data-coproperty-card-target="dots">
                  <i class="fa-solid fa-ellipsis-vertical"></i>
                </div>
              </div>
        <% end %>



    </div>
  </div>
</div>

app/views/coproperties/new.html.erb
  <div class="container" data-controller="coproperty-new">

    <div class="" style="position: absolute; bottom: 0; right: 32px;">
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="" style="position: absolute; bottom: 0; left: 32px; transform: rotateY(180deg);">
      <%= image_tag "man-with-paper.svg" %>
    </div>
   
    <%= render "form" %>

  </div>

app/views/coproperties/show.html.erb
<div class="container content-view">
  <%= @coproperty.coproperty_name %>
  <%# Budget card %>
  <div class="col-xl-3 col-sm-6 col-12">
    <%# <div class="d-flex justify-content-between flex-wrap"></div> %>
    <div class="card shadow border-0">
      <div class="card-body">
          <div class="row">
              <div class="col">
                <span class="h5 font-bolder text-muted text-sm d-block mb-2">Budget</span>
                <span class="h3 font-bold mb-5">$<%= @budget ? @budget.budget_amount : 0 %></span>
                <span class="h6 font-semibold text-muted text-sm d-block my-2">Statut:&nbsp;<%= @budget.budget_status %></span>
                <span class="h6 font-semibold text-muted text-sm d-block mb-2">Type:&nbsp;<%= @budget.budget_type %></span>

            </div>
            <div class="col-auto">
                <div class="icon icon-shape budget text-white text-lg rounded-circle">
                    <i class="fa-solid fa-money-check-dollar"></i>
                </div>
            </div>
        </div>
        <div class="mt-2 mb-0 text-sm">
            <span class="badge badge-pill bg-soft-success text-success me-2">
                <i class="fa-solid fa-check"></i>
            </span>
            <span class="text-nowrap text-xs text-muted">sur la cible</span>
        </div>
      </div>
    </div>
  </div>
  <%# /Budget Card %>
  <%# Expenses Card %>
  <div class="col-xl-3 col-sm-6 col-12">
    <div class="card shadow border-0">
      <div class="card-body">
          <div class="row">
              <div class="col">
                <span class="h5 font-bolder text-muted text-sm d-block mb-2">Expenses</span>
                <span class="h3 font-bold mb-5">$<%= @expenses.expense_amount %></span>
                <span class="h6 font-semibold text-muted text-sm d-block my-2">Statut:&nbsp;<%= %></span>

            </div>
            <div class="col-auto">
                <div class="icon icon-shape expenses text-white text-lg rounded-circle">
                    <i class="fa-solid fa-money-check-dollar"></i>
                </div>
            </div>
        </div>
        <div class="mt-2 mb-0 text-sm">
            <span class="badge badge-pill bg-soft-success text-success me-2">
                <i class="fa-solid fa-check"></i>
            </span>
            <span class="text-nowrap text-xs text-muted">done</span>
        </div>
      </div>
    </div>
  </div>
  <%# /Expenses Card %>

</div>