config/routes.rb
Rails.application.routes.draw do
  get 'link/show'
    #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(user) { user.admin? } do
    #mount Blazer::Engine, at: "blazer"
  end

  # Defines the root path route ("/")

  resources :syndics do
    resources :coproperties do
      resources :owners
      resources :budgets
      resources :expenses
      resources :payments, except: [:create]
      resources :messages, only: [:create, :index, :delete]
      resources :properties
      resources :requests, except: [:create, :delete]
    end
  end

  resources :owners do
    resources :coproperties, only: [:show] do
      resources :budgets, only: [:show, :index]
      resources :expenses, only: [:show, :index]
      resources :payments, only: [:new, :create, :show, :index]
      resources :messages, only: [:create, :index]
      resources :properties, only: [:show, :index]
      resources :requests, only: [:new, :create, :show, :index]
    end
  end

  resources :users do
    resources :owners
  end

  resources :coproperties do
    resources :owners, only: [:index]
  end

  get '/syndics/:syndic_id/coproperties/:coproperty_id/dashboard', to: 'pages#syndic_dashboard', as: 'syndic_dashboard'
  get '/owners/:owner_id/coproperties/:coproperty_id/dashboard', to: 'pages#owner_dashboard', as: 'owner_dashboard'


  post '/expenses/:id/up_vote', to: 'expenses#up_vote', as: 'upvote_expense'
  post '/expenses/:id/down_vote', to: 'expenses#down_vote', as: 'downvote_expense'

 get '/links/:id', to: 'links#show', as: 'link'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :owner, optional: true
  belongs_to :coproperty
  has_many :payments, dependent: :destroy
  has_many :budgets, through: :payments
  has_many :links, dependent: :destroy
  has_many :requests, dependent: :destroy

  def paid
    self.payments && self.payments.where("payment_status = 'Reçu'").count != 0
    # self.payments.where(payment_status: "Reçu").sum(:amount)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    if current_user.is_syndic?
      @properties = current_user.syndic.coproperties.first.properties
      @coproperty = Coproperty.find(params[:coproperty_id])
    else
      @properties = current_user.owner.properties
    end
  end

  def show
    @property = Property.find(params[:id])
    @requests = @property.requests
  end

  def new
    @property = Property.new
    @coproperty = Coproperty.find(params[:coproperty_id])
    @syndic = current_user.syndic
  end

  def create
    @property = Property.new(property_params)
    @property.coproperty_id = current_user.syndic.coproperties.first.id
    if @property.save
      Link.create(property_id: @property.id)
      redirect_to syndic_coproperty_properties_path(current_user.syndic, Coproperty.find(params[:coproperty_id])), :notice => "Propriété créée!"
    else
      render :action => 'new'
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    if @property.update_attributes(property_params)
      redirect_to @property, :notice  => "Propriété mise à jour!"
    else
      render :action => 'edit'
    end
  end

  def delete
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to properties_url, :notice => "Propriété supprimée!"
  end

private

  def property_params

    params.require(:property).permit(:owner_id, :address, :building, :floor, :property_number, :total_property_area, :payment_frequency, :coproperty_id)

  end

end

app/views/properties/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h2>Fiche de Propriété</h2>

        <%= simple_form_for [ @syndic, @coproperty, @property] do |f| %>
        <%= f.input :property_number, :label => 'Numéro de propriété' %>
        <%= f.input :floor, :label => 'Étage' %>
        <%# conditionner par type de copro multi-immeuble %>
        <%= f.input :building, :label => 'Immeuble' %>
        <%= f.input :total_property_area, :label => 'Surface Totale', :hint => 'Surface Totale de la propriété (incluant parking et box titrés), en m²' %>
        <%# <%= f.input :payment_frequency , collection: ['Mensuelle','Trimestrielle', 'Annuelle'], :label => 'Fréquence de Paiement', :hint => 'Fréquence de Paiement des frais de copropriété' %>
        <%= f.input :photo, :label => 'Photo',:hint => 'Ajoutez une photo de la copropriété', as: :file %>
          <div class="d-flex flex-wrap justify-content-end">
            <%= f.submit 'Créer',class: "btn btn-primary w-100 " %>
          </div>
        <% end %>
      </div>

app/views/properties/_property-form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h2>Formulaire habitation à compléter</h2>

        <%= simple_form_for @property do |f| %>
        <%= f.input :building %>
        <%= f.input :property_number %>
        <%= f.input :total_property_area %>
        <%= f.input :payment_frequency:['Mensuelle','Trimestrielle', 'Annuelle']%>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>

app/views/properties/_show.html.erb
<div class="d-flex justify-content-center flex-wrap" >
  <div style="width: 65%; margin: 2rem;">
    <div class="card p-relative property-card mx-5 mt-5 shadow">
      <div class="p-absolute p-3 close-btn" data-action="click->popup-window#hidePopup">
        <i class="fa-solid fa-xmark"></i>
      </div>
      <div class="row no-gutters">
        <div class="col-sm-5 p-relative prop-img">
          <div class="p-absolute dots-menu blur d-none" data-coproperty-card-target="dropDown" data-action="mouseout->coproperty-card#toggleMenu">
            <% if current_user.is_syndic? %>
            <% end %>
          </div>
          <%# three dots %>
          <div class="p-absolute three-dots blur d-none" data-action="click->coproperty-card#toggleMenu" data-coproperty-card-target="dots">
            <i class="fa-solid fa-ellipsis-vertical"></i>
          </div>
          <%# %>
          <%= image_tag "https://source.unsplash.com/random/?living,room", class: "product-image img" %>
        </div>
        <div class="p-absolute gradient lite-blur">
          <% if @property.owner && !@property.owner.photo.key.nil? %>
            <%= cl_image_tag @property.owner.photo.key, class: "rounded-circle shadow-1-strong owner-sm-img", width:"150", height:"150" %>
          <% else %>
            <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80", class: "rounded-circle shadow-1-strong owner-sm-img", width:"150", height:"150" %>
          <% end %>
          <% if !@property.owner.nil? %>
            <span class="ms-2"><%= @property.owner.full_name %></span>
          <% else %>
            <span class="ms-2">Aucun propriétaire</span>
          <% end %>
        </div>
        <div class="col-sm-7 info">
          <div class="card-body">
            <div class="h1 card-title title text-left mb-4">Propriété N°: </strong><%= @property.property_number %></div>
            <div class="h5 card-text"><strong>Étage : </strong><%= @property.floor %></div>
            <div class="h5 card-text"><strong>Superficie totale : </strong><%= @property.total_property_area %>&nbsp;m²</div>
            <div class="h5 card-text"><strong>Fréquence de Paiement : </strong><%= @property.payment_frequency %></div>
          </div>
        </div>
      </div>
    </div>
    </div>
      <% if current_user.is_syndic? %>
        <%= render "show_syndic" %>
      <% else %>
        <%= render "show_owner" %>
      <% end %>
    <div>
  </div>
</div>

app/views/properties/_show_owner.html.erb
<div class="m-4 card-border">
  <div class="container info-card card-dem">
    <div class="row">
      <span class="info-top col">
      <% @property.requests.each do |request| %>
        <h3><%= request.request_title %></h3>
        <p>Message: <%= request.message %></p>
        <p>Date de la requête: <%= request.request_date %></p>
        <p>Statut: <%= request.request_status %></p>
        <p>Documents: </p>
        <% request.photos.each do |photo| %>
          <%= cl_image_tag photo.key, alt: "Pièce justificative de #{request.object}"%>
        <% end %>
        <%= link_to "Modifier", edit_owner_coproperty_property_request_path(current_user.owner,@property.coproperty,@property,request), class: "" %>
      <% end %>
    </div>
  </div>

      <%= link_to "Nouvelle Requête", new_owner_coproperty_property_request_path(current_user.owner,@property.coproperty,@property), class: "" %>
      <%= link_to 'Précédent', owner_coproperty_path %>
    </div>
</div>

app/views/properties/_show_syndic.html.erb
<% if @property.owner.nil? %>
  <div class="card copy-card shadow mx-5 p-3">
    <h6 class="mb-3"> Lien à envoyer au propriétaire</h6>
    <div id="copy-section" class="input-group" data-controller="clipboard" data-clipboard-feedback-text-value="Copié !">
      <input class="form-control clipboard-input" data-clipboard-target="input" type="text" value="<%=  link_path(Link.last) %>" readonly>
      <div class="input-group-append">
        <button class="btn btn-primary clipboard-button" data-action="click->clipboard#copy">Copier le lien</button>
      </div>
    </div>
    <p class="p-2 mb-0 mt-2">
      - Copiez ce lien et partagez le avec le propriétaire de cette propriété <br>
      - Grâce à ce lien, le propriétaire pourra créer son compte et rejoindre l'espace de la copropriété sur Cojari <br>
      - Veuillez noter que ce lien est à utilisation unique par propriété <br>
    </p>
  </div>
<% else %>
  <div class="card copy-card shadow mx-5 p-3 px-5 d-flex flex-row justify-content-evenly">
    <div style="margin-left: -16px !important;">
      <% if @property.owner && !@property.owner.photo.key.nil? %>
        <%= cl_image_tag @property.owner.photo.key, class: "rounded-circle shadow-1-strong owner-md-img" %>
      <% else %>
        <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80", class: "owner-md-img rounded-circle shadow-1-strong" %>
      <% end %>
    </div>
    <div class="ms-4 notification-content">
      <% if !@property.owner.nil? %>
        <span class="ms-3"><i class="fa-solid fa-user"></i>&nbsp;&nbsp;<strong><%= @property.owner.full_name %></strong></span>
      <% else %>
        <span class="ms-3">Aucun propriétaire</span>
      <% end %>
      <ul class="list-unstyled mt-2 ms-3">
        <li><i class="fa-solid fa-genderless"></i>&nbsp;&nbsp; <%= @property.owner.gender %></li>
        <li><i class="fa-solid fa-cake-candles"></i>&nbsp; <%= @property.owner.birth_date %></li>
        <li><i class="fa-solid fa-phone"></i>&nbsp; <%= @property.owner.phone_number %></li>
        <li><i class="fa-solid fa-envelope"></i>&nbsp; <%= @property.owner.user.email %></li>
        <li><i class="fa-solid fa-id-card"></i>&nbsp; <%= @property.owner.card_number %></li>
        <li><i class="fa-solid fa-hourglass-start"></i> &nbsp;Propriétaire depuis: <%= @property.owner.ownership_date %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
  <div class="container" data-controller="coproperty-new">
    <div class="container">
    <h2>>Modifier propriété</h2>
      <div class="mt-3" style="z-index: 99;">
        <%= render "form", property: @property %>
      </div>
    <div class="bg-img-l" >
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="bg-img-r">
      <%= image_tag "man-with-paper.svg" %>
    </div>
  </div>

app/views/properties/index.html.erb
<div class="container mt-2">
  <%# top bar %>
  <div data-controller="profile-popup">
    <%# profile container %>
    <div class="p-absolute profile-popup d-none" data-profile-popup-target="profileContainer">
      <% @syndic = current_user.syndic %>
      <% @coproperties = current_user.syndic.coproperties %>
      <%= render "syndics/show" %>
    </div>
    <%# top container %>
    <div class="container map-container mx-2 my-4 d-flex justify-content-between align-items-center ">
      <div>
        <h1 class="fw-semibold text-left fade-font property-title txt-raleway p-0">
          <%= @coproperty.coproperty_name %>
        </h1>
        <span class="h6 text-muted"><i class="fa-solid fa-location-dot"></i>&nbsp;&nbsp;<%= @coproperty.address %></span>
        <span class="h6 text-muted">&nbsp;&nbsp;<i class="fa-solid fa-chart-area"></i>&nbsp;&nbsp;<%= @coproperty.coprop_private_area + @coproperty.coprop_private_area %>&nbsp;m²</span>
      </div>
      <div class="profile-div ">
        <% if current_user.is_syndic? %>
          <%= link_to "Ajouter une propriété" , new_syndic_coproperty_property_path(current_user.syndic), class: "btn btn-primary fw-semibold" %>
        <% end %>
        <div class=" w-auto m-4 " data-action="click->profile-popup#toggleProfile">
          <%= image_tag 'syndic', class: "rounded-circle shadow-1-strong small-profile mt-0", width:"150", height:"150" %>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-4 d-flex justify-content-start flex-wrap ">
    <% @properties.each do |p| %>
      <div class="cop-card shadow prop-index-card prop-hover" data-controller="popup-window" data-popup-window-prop-value="<%= p.id %>" data-action="click->popup-window#showPopup">
        <div class="row no-gutters">
          <div class="col-sm-5 frame">
            <%= image_tag "https://images.unsplash.com/photo-1664961793121-76acd727ba3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", class: "product-image img" %>
          </div>
          <div class="info d-flex flex-row">
            <div class="card-body">
              <div class="m-3">
                <div class="mx-1">
                  <i class="fa-solid fa-house"></i>&nbsp;Numéro de propriété :&nbsp;<%=p.property_number%>
                </div>
                <div class="mx-1 text-justify text-truncate para mb-0">
                  <i class="fa-solid fa-location-dot"></i>&nbsp;Étage :&nbsp;<%= p.floor %>
                </div>
                <p class="mx-1">
                  <i class="fa-solid fa-map"></i> &nbsp;Surface totale :&nbsp;<%=p.total_property_area%>m²
                </p>
                <% if p.paid %>
                  <p class="text-success mx-1">
                    <i class="fa-solid fa-receipt"></i>&nbsp;&nbsp;<%= "Payé" %>
                  </p>
                <% else %>
                  <p class="text-warning mx-1">
                    <i class="fa-solid fa-receipt"></i>&nbsp;&nbsp;<%= "Non Payé" %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="blur wall d-none" data-popup-window-target="popup">
          <% @property = p%>
          <%= render "properties/show" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
  <div class="container" data-controller="coproperty-new">
    <div class="container">
    <div class="bg-img-l" >
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="bg-img-r">
      <%= image_tag "man-with-paper.svg" %>
    </div>
    <%# <h2>Ajout nouvelle propriété</h2> %>
      <div class="mt-3" style="z-index: 99;">
         <%= render "form", property: @property %>
      <%= link_to 'Précédent', syndic_coproperty_properties_path %>
      </div>

  </div>