config/routes.rb
Rails.application.routes.draw do
  get 'link/show'
    #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(user) { user.admin? } do
    #mount Blazer::Engine, at: "blazer"
  end

  # Defines the root path route ("/")

  resources :syndics do
    resources :coproperties do
      resources :owners
      resources :budgets
      resources :expenses
      resources :payments, except: [:create]
      resources :messages, only: [:create, :index, :delete]
      resources :properties
      resources :requests, except: [:create, :delete]
    end
  end

  resources :owners do
    resources :coproperties, only: [:show] do
      resources :budgets, only: [:show, :index]
      resources :expenses, only: [:show, :index]
      resources :payments, only: [:new, :create, :show, :index]
      resources :messages, only: [:create, :index]
      resources :properties, only: [:show, :index]
      resources :requests, only: [:new, :create, :show, :index]
    end
  end

  resources :users do
    resources :owners
  end

  resources :coproperties do
    resources :owners, only: [:index]
  end

  get '/syndics/:syndic_id/coproperties/:coproperty_id/dashboard', to: 'pages#syndic_dashboard', as: 'syndic_dashboard'
  get '/owners/:owner_id/coproperties/:coproperty_id/dashboard', to: 'pages#owner_dashboard', as: 'owner_dashboard'


  post '/expenses/:id/up_vote', to: 'expenses#up_vote', as: 'upvote_expense'
  post '/expenses/:id/down_vote', to: 'expenses#down_vote', as: 'downvote_expense'

 get '/links/:id', to: 'links#show', as: 'link'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :find_expense, only: [:show, :edit, :update]

  def index
    @expenses = Expense.all
    @coproperty = Coproperty.find(params[:coproperty_id])
  end

  def show
  end

  def new
    @expense = Expense.new
    @coproperty = Coproperty.find(params[:coproperty_id])
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
    redirect_to  syndic_coproperty_expenses_path, :notice => "Dépense créée !"
    else
    render :action => 'new'
    end
  end

  def edit
    @coproperty = Coproperty.find(params[:coproperty_id])
  end

  def update
    if @expense.update(expense_params)
    redirect_to syndic_coproperty_expenses_path, :notice  => "Dépesne mise à jour!"
    else
    render :action => 'edit'
    end
  end

# Test Votes

  def up_vote
    @expense = Expense.find(params[:id])
    @vote = ExpenseVote.new
    @vote.vote_up = true
    @vote.owner = current_user.owner
    @vote.expense = @expense
    @vote.save!
  end

  def down_vote
    @expense = Expense.find(params[:id])
    @vote = ExpenseVote.new
    @vote.vote_up = false
    @vote.owner = current_user.owner
    @vote.expense = @expense
    @vote.save!
  end

private

  def expense_params
    params.require(:expense).permit(:expense_name, :expense_type, :expense_amount, :expense_date, :expense_status, :budget_id, photos: [])
  end

  def find_expense
    @expense = Expense.find(params[:id])
  end
end

app/views/expenses/_create_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h2>Fiche de Frais</h2>

        <%= simple_form_for [current_user.syndic, @coproperty, @expense] do |f| %>
        <%= f.input :expense_name, :label => 'Titre', :hint => 'Donnez un titre à ce frais' %>
        <%= f.input :expense_type, collection:['Nettoyage','Jardinage','Gardiennage','Eau / Electricité','Sécurité','Maintenance','Consommables','Frais Juridiques','Evénements','Autres Frais'], :label => 'Type', :hint => 'Sélectionnez le type de frais à ajouter' %>
        <%= f.input :expense_amount, :label => 'Montant', :hint => 'Montant du frais en chiffres, dirham marocain',:placeholder => '2000' %>
        <%= f.input :photos,:label => 'Pièces Justificatives',:hint => 'Vous pouvez joindre des documents ou photos pour justifier ce frais', as: :file, input_html: { multiple: true } %>
        <%= f.association :budget,:label => 'Budget Rattaché', as: :select, :label_method => lambda { |budget| "#{budget.budget_title}" } , :hint => 'Sélectionnez le budget rattaché à ce frais' %>
        <%= f.submit 'Soumettre', class: "btn btn-default btn-primary" %>
        <% end %>

app/views/expenses/_update_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow" data-controller="conditional-input">

        <h2>Fiche de Frais</h2>

        <%= simple_form_for [current_user.syndic, @coproperty, @expense] do |f| %>
        <%= f.input :expense_name, :label => 'Titre', :hint => 'Donnez un titre à ce frais' %>
        <%= f.input :expense_type, collection:['Nettoyage','Jardinage','Gardiennage','Eau / Electricité','Sécurité','Maintenance','Consommables','Frais Juridiques','Evénements','Autres Frais'], :label => 'Type', :hint => 'Sélectionnez le type de frais à ajouter' %>
        <%= f.input :expense_amount, :label => 'Montant', :hint => 'Montant du frais en chiffres, dirham marocain',:placeholder => '2000' %>
        <%= f.input :expense_status, input_html:{"data-action":"change->conditional-input#toggle"}, collection:['Proposé','Validé','Refusé','Payé'], :label => 'Statut', :hint => 'Modifiez le statut du frais' %>
        <%= f.input(:expense_date,
        :label => 'Date de Paiement',
        :hint => 'Précisez quand le paiement a été effectué',
        wrapper_html:{"data-conditional-input-target":"date", class: "d-none"})%>
        <%= f.input :photos, :label => 'Pièces Justificatives',:hint => 'Vous pouvez joindre des documents ou photos pour justifier ce frais', as: :file, input_html: { multiple: true } %>
        <%= f.submit 'Soumettre', class: "btn btn-default btn-primary" %>
        <%# <%= link_to 'Précédent',  syndic_coproperty_expense_path %>
        <% end %>

app/views/expenses/_vote_form.html.erb
<% if !current_user.is_syndic? %>
  <%= expense.expense_name %>
  <%= link_to upvote_expense_path(expense), data:{"turbo-method": :post}, confirm: 'Vote ?', class: 'link-vote-up', 'data-message' => 'Are you sure?', :remote => true do %>
    <i class="fa-solid fa-thumbs-up"></i>
    <%= expense.expense_votes.nil? ? 0 : expense.expense_votes.pluck(:vote_up).count(true) %>
  <% end %>

  <%= link_to downvote_expense_path(expense), data:{"turbo-method": :post}, confirm: 'Vote ?', class: 'link-vote-up', 'data-message' => 'Are you sure?', :remote => true do %>
    <i class="fa-solid fa-thumbs-down"></i>
    <%= expense.expense_votes.nil? ? 0 : expense.expense_votes.pluck(:vote_up).count(false) %>
  <% end %>
<% else %>
  <%= expense.expense_name %>
  <br>
  votes pour : <%= expense.expense_votes.nil? ? 0 : expense.expense_votes.pluck(:vote_up).count(true) %>
  <br>
  votes contre : <%= expense.expense_votes.nil? ? 0 : expense.expense_votes.pluck(:vote_up).count(false) %>
<% end %>

app/views/expenses/edit.html.erb
 <div class="container" data-controller="coproperty-new">
  <div class="container">
    <div class="bg-img-l" >
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="bg-img-r">
      <%= image_tag "man-with-paper.svg" %>
    </div>
    <%# <h2>Ajout nouvelle propriété</h2> %>
    <div class="mt-3" style="z-index: 99;">
      <%= render "update_form", expense: @expense %>
      <%= link_to 'Précédent', syndic_coproperty_expenses_path(@expense) %>
    </div>
  </div>
</div>

app/views/expenses/form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">

        <h2>Fiche de Frais</h2>

        <%= simple_form_for @expense do |f| %>
        <%= f.input :expense_name %>
        <%= f.input :expense_status, collection:['Proposé','Validé','Refusé','Payé'] %>
        <%= f.input :expense_type, collection:['Nettoyage','Jardinage','Gardiennage','Eau / Electricité','Sécurité','Maintenance','Consommables','Frais Juridiques','Evénements','Autres Frais'] %>
        <%= f.input :expense_date %>
        <%= f.input :expense_amount %>
        <%= f.input :photo %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>

app/views/expenses/index.html.erb
<div class="container pt-3">
<%= link_to "Nouveau Frais", new_syndic_coproperty_expense_path(current_user.syndic, @coproperty), class: "btn btn-primary fw-semibold", style: "float: right;" %>
<table id="my-table">
    <tr>
      <th>Titre</th>
      <th>Montant (dhs)</th>
      <th>Type</th>
      <th>Date de Paiement</th>
      <th>Budget Rattaché</th>
      <th>Statut</th>
      <th>Justif</th>
      <th>Actions</th>
    </tr>
  <% @expenses.each do |expense| %>
  <% type = expense.expense_type == "Nettoyage" ? "blue" : expense.expense_type == "Jardinage" ? "green" : expense.expense_type == "Consommables" ? "pink" : expense.expense_type == "Sécurité" ? "yellow" : expense.expense_type == "Maintenace" ? "orange" : "red" %>
    <tr>
      <td class="fw-medium"> <%= expense.expense_name %> </td>
      <td><%= expense.expense_amount.to_i %></td>
      <td><span class="badge <%= type %>"><%= expense.expense_type %></span></td>
      <td><%= expense.expense_date %></td>
      <td><%= expense.budget.budget_title %></td>
      <td><%= expense.expense_status %></td>
      <%# IF WE WANT TO ADD ICON TO CELL : %>
      <%# <td><i class="fa-solid fa-pen-to-square "></i><span class="badge <%= status %>
      <td class= "text-center">
      <% if expense.photos.count != 0 %>
        <%= link_to expense.photos.first do %>
          <i class="fa-solid fa-file"></i>
        <% end %>
      <% else %>
        <%= link_to "https://res.cloudinary.com/dn7adx3jz/image/upload/v1668253363/facture-nettoyage_t22dwy.png" do %>
          <i class="fa-solid fa-file"></i>
        <% end %>
      <% end %>

      <td class= "text-center">
        <%= link_to edit_syndic_coproperty_expense_path(current_user.syndic,expense.budget.coproperty,expense.id) do %>
          <i class="fa-solid fa-pen-to-square "></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/expenses/index_test.html.erb
<div class="px-5 card pt-3">
  <div class="inline-container p-3">
      <% @expenses.each do |expense| %>
        <div class="slide-container">
          <%# <div class="wrapper"> %>
            <div class="clash-card barbarian btns">
              <div class="clash-card__image clash-card__image--barbarian">
              </div>
              <div class="clash-card__level clash-card__level--barbarian"><%= expense.expense_name %></div>
              <div class="clash-card__unit-name">Type : <%= expense.expense_type %></div>
              <div class="clash-card__unit-name">Montant :<%= expense.expense_amount.to_i %> MAD</div>
              <%# <%# <div class="clash-card__unit-name"><%= expense.expense_status % !! à voir statut dans le edit> %>
              <div class="clash-card__unit-description">
              </div>
              <%= render "expenses/vote_form", expense: expense %>
              <%= link_to "Détails", syndic_coproperty_expense_path(current_user.syndic,expense.budget.coproperty,expense.id), class: "bttn btn-main" %>
              <hr/>
            </div>
        </div>
      <% end %>

    </div>

  <%= link_to "Nouveau", new_syndic_coproperty_expense_path(current_user.syndic, @coproperty) %>

</div>

app/views/expenses/new.html.erb
 <div class="container" data-controller="coproperty-new">
  <div class="container">
    <div class="bg-img-l" >
      <%= image_tag "coproperty-creation.svg" %>
    </div>
    <div class="bg-img-r">
      <%= image_tag "man-with-paper.svg" %>
    </div>
    <%# <h2>Ajout nouvelle propriété</h2> %>
    <div class="mt-3" style="z-index: 99;">
      <%= render "create_form", expense: @expense %>
      <%= link_to 'Précédent', syndic_coproperty_expenses_path %>
    </div>
  </div>
</div>

app/views/expenses/show.html.erb
<div class="m-4 card-border">
  <div class="container info-card card-dem">
    <div class="row">
      <span class="info-top col">
        <h1><%= @expense.expense_name %></h1>
        <%# <%# <h3><%= @expense.expense_date % !! should only be added when status is paid> %>
        <h3>Montant : <%= @expense.expense_amount.to_i %> MAD</h3>
        <h3>Type de Frais : <%= @expense.expense_type %></h3>
         <h3>Statut du Frais : <%= @expense.expense_status %></h3>
        <div class="info-bottom col-8 search-btns">
        </div>
        <h2>Documents</h2>
        <% @expense.photos.each do |photo| %>
          <%= cl_image_tag photo.key, alt: "Pièce justificative de #{@expense.expense_name}"%>
        <% end %>
      </span>
    </div>
  </div>

      <%= link_to "Modifier",  edit_syndic_coproperty_expense_path(@expense.id), class: "" %>
      <%= link_to 'Précédent',  syndic_coproperty_expenses_path %>
    </div>
</div>
</div>
</div>

<%# <%= render "layouts/footer" %>





</div>